[package]
name = "wgpu-instancing"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.22.0"
cgmath = "0.18.0"
image = "0.25.6"
log = "0.4.27"
pollster = "0.4.0"
pretty_env_logger = "0.5.0"
rand = "0.9.0"
wgpu = "24.0.3"
winit = "0.30.9"
